version: '3.8'

services:
  wol-switch:
    image: lostome/wol_secure_lightswitch:latest
    platform: linux/arm64 # or linux/amd64
    container_name: wol_secure_lightswitch
    restart: unless-stopped
    network_mode: host # fundamental for wake on lan
    environment:
      - PORT=7500 # change this port to your own liking
      - TZ=Europe/Rome # change this to your desired timezone
      - JWT_SECRET="your_very_long_and_random_jwt_secret" #change this to a very long and hard to guess string
      - GIN_MODE=release 
    volumes:
      - ./data:/app/data # here you have to put your hosts.yaml. Follow the example in hosts.yaml.example
      - /home/user/.ssh:/app/data/.ssh:ro # this is needed for key-based auth if you want to use it