version: '3.8'

services:
  wol-switch:
    image: lostome/wol_secure_lightswitch:latest
    platform: linux/arm64 # or linux/amd64
    container_name: wol_secure_lightswitch
    restart: unless-stopped
    network_mode: host # fundamental for wake on lan
    environment:
      - PORT=7500 # change this port to your own liking
      - TZ=Europe/Rome # change this to your desired timezone
    volumes:
      - ./data:/app/data # here you have to put your hosts.yaml. Follow the example in hosts.yaml.example
