# list of hosts to send WoL packets to, along with their shutdown commands and credentials for SSH (if needed)
# only id, name and mac are need for wol, the rest is for shutdown
- id: server-proxmox
  name: "Proxmox Node 1"
  mac: "04:92:26:D5:69:58"
  ip: "192.168.1.80" # you can also use the hostname if it resolves correctly from the WOL server
  user: "switchbot"
  password: "Dx0R4zv3QoxC"
  key_path: #"/root/.ssh/id_rsa" #leave empty if not using key-based auth
  cmd: "sudo -n /usr/sbin/shutdown -h now"
  skip_interfaces: ["Tailscale", "vEthernet", "Loopback", "Bluetooth"] #case sensitive, relative to the interfaces of the WOL server, not the host receiver
